//! Schema v6 manifest support — per-platform-leaf design + embedded blob.
//!
//! Issue #861 of meta #853. Adopts the
//! [`zackees/clang-tool-chain-bins`](https://github.com/zackees/clang-tool-chain-bins/tree/main/assets/clang)
//! manifest shape: a top-level index keyed by `<owner>/<repo>`, each
//! tool keyed by host triple, each host-triple leaf carrying a
//! `latest` pointer plus a version-keyed nested map:
//!
//! ```json
//! {
//!   "schema_version": 6,
//!   "tools": {
//!     "zackees/zccache": {
//!       "x86_64-pc-windows-msvc": {
//!         "latest": "1.12.9",
//!         "1.12.9": {
//!           "href":   "https://media.githubusercontent.com/media/.../zccache-x86_64-pc-windows-msvc.zip",
//!           "sha256": "0000...64hex"
//!         },
//!         "1.12.8": { "href": "...", "sha256": "..." }
//!       }
//!     }
//!   }
//! }
//! ```
//!
//! Two things land in this module:
//!
//! 1. **The runtime parser + lookup.** `ManifestV6::from_json` reads the
//!    shape above; `ManifestV6::lookup(owner, repo, triple)` resolves
//!    either the leaf's `latest` or a caller-supplied pin to the
//!    `{href, sha256}` pair.
//!
//! 2. **The embedded blob.** `build.rs` zstd-compresses
//!    `embed/manifest.json` into `${OUT_DIR}/manifest.json.zst` at
//!    compile time; [`embedded_manifest`] decompresses + parses it
//!    lazily through a process-wide [`OnceLock`]. The intent is that
//!    runtime lookups never touch the network — the live fetch from
//!    `raw.githubusercontent.com` remains as a fallback for resources
//!    not yet in the embed (e.g. brand-new releases between soldr
//!    versions).
//!
//! For THIS PR the embedded blob is intentionally an empty schema-v6
//! envelope so the runtime path exists end-to-end without committing to
//! a specific manifest snapshot. A follow-up sub-issue under #853 will
//! wire the materialization pipeline that pulls the latest snapshot off
//! the `manifest` branch at release time (analogous to how a managed
//! tool pin is bumped).
//!
//! ## Prerelease filtering
//!
//! Stable releases only — see [`is_stable_version_tag`]. A tag like
//! `v1.0.0-rc1` / `v1.0.0-alpha.3` / `v1.0.0-beta` / `v1.0.0.dev1` is
//! rejected by the publish-side helper before it ever lands in a leaf.
//! The runtime parser is permissive (it will surface whatever the
//! manifest publishes) so a misconfigured publisher cannot silently
//! make every install unresolvable; the regex is the publish-side
//! guard, exposed here for unit-testability.

use std::collections::HashMap;
use std::io::Read;
use std::sync::OnceLock;

use serde::Deserialize;

/// Embedded zstd-compressed v6 manifest, generated by `build.rs` from
/// `embed/manifest.json`. See module docs.
const EMBEDDED_MANIFEST_ZST: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/manifest.json.zst"));

/// Top-level v6 manifest shape. `schema_version` is a discriminator on
/// the wire so the parser can fast-fail mismatched schemas, and so
/// future bumps (v7, …) can co-exist in checked-in snapshots during
/// migrations.
#[derive(Debug, Clone, Deserialize)]
pub struct ManifestV6 {
    pub schema_version: u32,
    #[serde(default)]
    pub tools: HashMap<String, HashMap<String, V6Leaf>>,
}

/// One host-triple leaf: `{latest, "<version>": {href, sha256}, ...}`.
///
/// The version keys are stored in a free-form `HashMap<String, V6Asset>`
/// so the leaf is a single JSON object on the wire — the same shape
/// clang-tool-chain-bins ships. The version strings are bare (`"1.12.9"`,
/// not `"v1.12.9"`) and the lookup is exact, so callers must normalize
/// before querying.
#[derive(Debug, Clone, Deserialize)]
pub struct V6Leaf {
    /// The version key that callers resolve to when no explicit pin is
    /// supplied. Defaults to the empty string when absent so a parser
    /// error here doesn't crash the load — `lookup_*` callers treat an
    /// empty string as "no latest declared".
    #[serde(default)]
    pub latest: String,
    /// The version-keyed asset map, flattened into the same JSON object
    /// as `latest`. `#[serde(flatten)]` lets us emit the shape
    /// clang-tool-chain-bins uses without the extra `versions` wrapper.
    #[serde(flatten)]
    pub versions: HashMap<String, V6Asset>,
}

/// One `(href, sha256)` pair — the unit the resolver actually downloads.
#[derive(Debug, Clone, Deserialize, PartialEq, Eq)]
pub struct V6Asset {
    pub href: String,
    pub sha256: String,
}

/// The `lookup` result. Holds the resolved version (so the cache layer
/// can place the artifact under `~/.soldr/bin/<name>-<version>/`) and
/// the `(href, sha256)` of the matched leaf entry.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct V6Hit<'a> {
    pub version: String,
    pub asset: &'a V6Asset,
}

impl ManifestV6 {
    /// The schema version this module knows how to parse. The runtime
    /// parser accepts only this exact value — older shapes are routed
    /// through the legacy v5 path in `manifest_lookup.rs`.
    pub const SCHEMA_VERSION: u32 = 6;

    /// Parse a v6-shaped JSON body. Returns `None` (not an error) on
    /// any failure so the embedded-blob load + live-fetch fallback can
    /// degrade silently when a malformed manifest lands in the wild.
    pub fn from_json(body: &str) -> Option<Self> {
        let parsed: Self = serde_json::from_str(body).ok()?;
        if parsed.schema_version != Self::SCHEMA_VERSION {
            return None;
        }
        Some(parsed)
    }

    /// Build the `<owner>/<repo>` tool key. Centralized so callers
    /// can't drift from the publish-side spelling.
    pub fn tool_key(owner: &str, repo: &str) -> String {
        format!("{owner}/{repo}")
    }

    /// Resolve `(owner, repo, host_triple)` to an asset, picking the
    /// pinned version when one is supplied, otherwise the leaf's
    /// `latest`. A leaf with neither a pin nor a `latest` returns
    /// `None`.
    pub fn lookup<'a>(
        &'a self,
        owner: &str,
        repo: &str,
        host_triple: &str,
        pin: Option<&str>,
    ) -> Option<V6Hit<'a>> {
        let key = Self::tool_key(owner, repo);
        let leaf = self.tools.get(&key)?.get(host_triple)?;
        let version = match pin {
            Some(v) if !v.is_empty() => v.to_string(),
            _ if !leaf.latest.is_empty() => leaf.latest.clone(),
            _ => return None,
        };
        let asset = leaf.versions.get(&version)?;
        Some(V6Hit { version, asset })
    }

    /// True when the manifest has at least one tool. Useful at startup
    /// to short-circuit the lookup hop when the embedded blob is the
    /// empty envelope (`{"schema_version":6,"tools":{}}`).
    pub fn is_empty(&self) -> bool {
        self.tools.is_empty()
    }
}

/// Decompress + parse the embedded zstd blob. Cached process-wide via
/// [`OnceLock`] so the cold-start cost (zstd decompress + serde parse)
/// is paid exactly once.
///
/// Returns `None` if the embedded blob fails to decompress or parse —
/// callers must treat this as "no embedded data, fall through to the
/// live manifest fetch" rather than a hard error, so a build-script
/// bug never wedges runtime resolution.
pub fn embedded_manifest() -> Option<&'static ManifestV6> {
    static CACHE: OnceLock<Option<ManifestV6>> = OnceLock::new();
    CACHE
        .get_or_init(|| {
            let mut decoder = zstd::stream::read::Decoder::new(EMBEDDED_MANIFEST_ZST).ok()?;
            let mut buf = String::new();
            decoder.read_to_string(&mut buf).ok()?;
            ManifestV6::from_json(&buf)
        })
        .as_ref()
}

/// Raw access to the embedded blob bytes — exposed so size-budget
/// tests can assert the compressed size without depending on the
/// process-wide cache being unset.
pub fn embedded_manifest_bytes() -> &'static [u8] {
    EMBEDDED_MANIFEST_ZST
}

/// Return `true` when `tag` looks like a stable release: `v?<major>.<minor>.<patch>`
/// with no trailing prerelease or build-metadata suffix.
///
/// Rejected: `v1.0.0-rc1`, `1.0.0-alpha.3`, `v1.0.0.dev1`, `1.0.0+build7`,
/// `1.0.0-beta`, `1.0.0-pre`, `1.0.0-snapshot`.
///
/// This is the publish-side filter: the nightly refresh on the
/// `manifest` branch is expected to drop everything for which this
/// returns `false`. Exposed here (and unit-tested) so the regex lives
/// in one place and the consumer + publisher can never drift.
pub fn is_stable_version_tag(tag: &str) -> bool {
    let trimmed = tag.trim_start_matches('v');
    let mut parts = trimmed.split('.');
    let Some(major) = parts.next() else {
        return false;
    };
    let Some(minor) = parts.next() else {
        return false;
    };
    let Some(patch) = parts.next() else {
        return false;
    };
    // Strict numeric major.minor.patch. The patch segment must be
    // pure digits — `1.0.0-rc1` would put `0-rc1` here and fail.
    if parts.next().is_some() {
        // No trailing `.dev1`, `.0`, etc. components allowed beyond
        // major.minor.patch. (Skips four-component versions; those
        // are rare for the tools soldr tracks. If a tracked tool ever
        // uses `1.0.0.0`, this is the single line to relax.)
        return false;
    }
    let all_digits = |s: &str| !s.is_empty() && s.chars().all(|c| c.is_ascii_digit());
    all_digits(major) && all_digits(minor) && all_digits(patch)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_v6_json() -> &'static str {
        r#"{
            "schema_version": 6,
            "tools": {
                "zackees/zccache": {
                    "x86_64-pc-windows-msvc": {
                        "latest": "1.12.9",
                        "1.12.9": {
                            "href":   "https://example.com/zccache-1.12.9-win.zip",
                            "sha256": "0000000000000000000000000000000000000000000000000000000000000000"
                        },
                        "1.12.8": {
                            "href":   "https://example.com/zccache-1.12.8-win.zip",
                            "sha256": "1111111111111111111111111111111111111111111111111111111111111111"
                        }
                    },
                    "aarch64-apple-darwin": {
                        "latest": "1.12.9",
                        "1.12.9": {
                            "href":   "https://example.com/zccache-1.12.9-mac-arm.tar.gz",
                            "sha256": "2222222222222222222222222222222222222222222222222222222222222222"
                        }
                    }
                }
            }
        }"#
    }

    #[test]
    fn v6_parser_roundtrip() {
        let m = ManifestV6::from_json(sample_v6_json()).expect("parse ok");
        assert_eq!(m.schema_version, 6);
        let hit = m
            .lookup("zackees", "zccache", "x86_64-pc-windows-msvc", None)
            .expect("should hit");
        assert_eq!(hit.version, "1.12.9");
        assert!(hit.asset.href.contains("1.12.9"));
    }

    #[test]
    fn v6_leaf_picks_latest_when_unpinned() {
        let m = ManifestV6::from_json(sample_v6_json()).unwrap();
        let hit = m
            .lookup("zackees", "zccache", "x86_64-pc-windows-msvc", None)
            .unwrap();
        assert_eq!(hit.version, "1.12.9");
        assert_eq!(hit.asset.sha256.chars().next(), Some('0'));
    }

    #[test]
    fn v6_leaf_respects_pin_override() {
        let m = ManifestV6::from_json(sample_v6_json()).unwrap();
        let hit = m
            .lookup(
                "zackees",
                "zccache",
                "x86_64-pc-windows-msvc",
                Some("1.12.8"),
            )
            .unwrap();
        assert_eq!(hit.version, "1.12.8");
        assert_eq!(hit.asset.sha256.chars().next(), Some('1'));
    }

    #[test]
    fn v6_pin_for_missing_version_returns_none() {
        let m = ManifestV6::from_json(sample_v6_json()).unwrap();
        let miss = m.lookup(
            "zackees",
            "zccache",
            "x86_64-pc-windows-msvc",
            Some("9.9.9"),
        );
        assert!(miss.is_none());
    }

    #[test]
    fn v6_missing_triple_returns_none() {
        let m = ManifestV6::from_json(sample_v6_json()).unwrap();
        assert!(m
            .lookup("zackees", "zccache", "i686-unknown-linux-gnu", None)
            .is_none());
    }

    #[test]
    fn v6_missing_tool_returns_none() {
        let m = ManifestV6::from_json(sample_v6_json()).unwrap();
        assert!(m
            .lookup("nobody", "nothing", "x86_64-pc-windows-msvc", None)
            .is_none());
    }

    #[test]
    fn v6_rejects_wrong_schema_version() {
        let bad = r#"{"schema_version": 5, "tools": {}}"#;
        assert!(ManifestV6::from_json(bad).is_none());
    }

    #[test]
    fn v6_rejects_malformed_json() {
        assert!(ManifestV6::from_json("not-json").is_none());
        assert!(ManifestV6::from_json("").is_none());
    }

    #[test]
    fn v6_empty_envelope_parses_and_misses_everything() {
        let m = ManifestV6::from_json(r#"{"schema_version": 6, "tools": {}}"#).unwrap();
        assert!(m.is_empty());
        assert!(m.lookup("a", "b", "x86_64-pc-windows-msvc", None).is_none());
    }

    #[test]
    fn v6_prerelease_versions_are_filtered_on_publish() {
        // Stable
        assert!(is_stable_version_tag("1.0.0"));
        assert!(is_stable_version_tag("v1.0.0"));
        assert!(is_stable_version_tag("v1.12.9"));
        assert!(is_stable_version_tag("0.1.73"));
        assert!(is_stable_version_tag("v21.1.5"));
        // Unstable
        assert!(!is_stable_version_tag("v1.0.0-rc1"));
        assert!(!is_stable_version_tag("1.0.0-rc.1"));
        assert!(!is_stable_version_tag("v1.0.0-alpha"));
        assert!(!is_stable_version_tag("1.0.0-alpha.3"));
        assert!(!is_stable_version_tag("v1.0.0-beta"));
        assert!(!is_stable_version_tag("1.0.0-beta.2"));
        assert!(!is_stable_version_tag("v1.0.0-pre"));
        assert!(!is_stable_version_tag("1.0.0-dev"));
        assert!(!is_stable_version_tag("1.0.0.dev1"));
        assert!(!is_stable_version_tag("v1.0.0-snapshot"));
        assert!(!is_stable_version_tag("1.0.0+build7"));
        // Malformed
        assert!(!is_stable_version_tag(""));
        assert!(!is_stable_version_tag("v1"));
        assert!(!is_stable_version_tag("v1.0"));
        assert!(!is_stable_version_tag("vX.Y.Z"));
        assert!(!is_stable_version_tag("1.0.0.0"));
    }

    #[test]
    fn embedded_blob_decompresses() {
        let m = embedded_manifest().expect("embedded blob must parse");
        assert_eq!(m.schema_version, ManifestV6::SCHEMA_VERSION);
        // The build script compresses the checked-in snapshot, so the
        // only invariant here is "parses + matches the expected schema
        // version".
    }

    #[test]
    fn embedded_blob_size_is_under_budget() {
        // Sanity bound: a populated v6 mono-manifest is expected to
        // sit comfortably under 2 MiB compressed. The empty envelope
        // is single-digit bytes; the budget catches accidental
        // commits of multi-MB blobs. Bump the constant when the
        // publish pipeline lands and real content arrives.
        const EMBED_SIZE_BUDGET_BYTES: usize = 2 * 1024 * 1024;
        assert!(
            embedded_manifest_bytes().len() < EMBED_SIZE_BUDGET_BYTES,
            "embedded manifest blob is {} bytes — over the {} byte budget",
            embedded_manifest_bytes().len(),
            EMBED_SIZE_BUDGET_BYTES
        );
    }

    #[test]
    fn embed_lookup_is_fast() {
        // Initialization must still parse the embedded blob, but cold zstd
        // decompression + serde parsing is a one-shot wall-clock sample. It
        // is scheduler-contended on target-run workers and cannot be sampled
        // again, so it is intentionally not a unit-test gate; measure it in a
        // dedicated performance environment instead. Keep the repeatable O(N)
        // lookup guard below instead.
        let budget = std::time::Duration::from_millis(250);

        // Initialize once so this test still verifies the embedded data is
        // available before exercising its lookup index.
        let m = embedded_manifest().expect("embedded blob must parse");

        // Per-lookup cost, best of three. This is the O(N) guard, and a real
        // regression makes every round slow -- so taking the minimum drops
        // transient scheduler noise without weakening what is being asserted.
        // A single sample cannot tell the two apart.
        let best = (0..3)
            .map(|_| {
                let started = std::time::Instant::now();
                for _ in 0..10_000 {
                    let _ = m.lookup("zackees", "zccache", "x86_64-pc-windows-msvc", None);
                }
                started.elapsed()
            })
            .min()
            .expect("three rounds");
        assert!(
            best < budget,
            "10k embedded-manifest lookups took {best:?} (best of 3), expected < {budget:?}"
        );
    }

    #[test]
    fn tool_key_is_owner_slash_repo() {
        assert_eq!(
            ManifestV6::tool_key("zackees", "zccache"),
            "zackees/zccache"
        );
    }
}
