"""Lint check: verify that version strings are consistent across all manifests."""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

SOURCES: list[tuple[str, str]] = [
    ("src/running_process/__init__.py", r'^__version__\s*=\s*"([^"]+)"'),
    ("pyproject.toml", r'^version\s*=\s*"([^"]+)"'),
    ("Cargo.toml", r'^version\s*=\s*"([^"]+)"'),
    # The Python extension crate pins its sibling by exact version. Left
    # behind, it does not merely drift -- `cargo publish` cannot resolve
    # it, so the release fails after the tag is already cut.
    (
        "crates/running-process-py/Cargo.toml",
        r'^running-process\s*=\s*\{[^}]*version\s*=\s*"([^"]+)"',
    ),
    # Same hazard, added with the probe crates (#651). Every path dependency
    # of a published crate needs a version -- optional ones behind a feature
    # included -- and a stale one is not caught until `cargo publish` refuses
    # the package, which is after the tag is cut.
    (
        "crates/running-process/Cargo.toml",
        r'^running-process-probe\s*=\s*\{[^}]*version\s*=\s*"([^"]+)"',
    ),
    (
        "crates/running-process-probe-daemon/Cargo.toml",
        r'^running-process\s*=\s*\{[^}]*version\s*=\s*"([^"]+)"',
    ),
    (
        "crates/running-process-probe-daemon/Cargo.toml",
        r'^running-process-probe\s*=\s*\{[^}]*version\s*=\s*"([^"]+)"',
    ),
    # `uv.lock` records the project's own version for the editable install.
    # It is regenerated by `uv lock`, which is easy to forget because nothing
    # fails without it -- it drifted to 4.6.2 and stayed there across several
    # releases, carrying a stale `ziglang` entry with it long after zig was
    # banned (#792). Checking it here is the only thing that makes the drift
    # visible before a release rather than never.
    (
        "uv.lock",
        r'^name = "running-process"\s+version = "([^"]+)"',
    ),
]


def _extract_version(path: Path, pattern: str) -> str | None:
    text = path.read_text(encoding="utf-8")
    match = re.search(pattern, text, re.MULTILINE)
    return match.group(1) if match else None


def main() -> int:
    versions: dict[str, str | None] = {}
    for relpath, pattern in SOURCES:
        versions[relpath] = _extract_version(ROOT / relpath, pattern)

    missing = [k for k, v in versions.items() if v is None]
    if missing:
        for name in missing:
            print(f"ERROR: could not extract version from {name}")
        return 1

    unique = set(versions.values())
    if len(unique) != 1:
        print("ERROR: version mismatch across manifests:")
        for name, ver in versions.items():
            print(f"  {name}: {ver}")
        return 1

    print(f"OK: all versions consistent ({unique.pop()})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
