"""Tests for the #3040 third-party-compile ratchet (soldr#3039 / soldr#3040).

The fixtures below build a synthetic (compile_journal.jsonl, cargo
fingerprint log, Cargo.lock) triple that exercises all four buckets
`analyze_compile_journal.analyze` classifies third-party crates into. This
pins two things across the T1/T2 seam: the journal record field names (the
real zccache schema, per the task spec) and a plausible `CARGO_LOG=cargo::
core::compiler::fingerprint=info` shape (`fingerprint dirty for ... cause:
<Reason>`, alongside a plain `Compiling <crate> vX.Y.Z` progress line -- both
of which cargo writes to stderr, the same stream this repo's CI tees into
one capture file). The analyzer (`analyze_compile_journal.py`) now exists,
and every test below drives the real join through it -- the fixture shapes
were checked against its `DIRTY_RE`, `STATUS_RE`, and `LOCKFILE_NAME_RE`
patterns and its cwd-based first/third-party classification, not guessed.
If a real run disagrees with this fixture, the fixture is the first thing
to check, not this script's own threshold logic.
"""

from __future__ import annotations

import json
from pathlib import Path

from _script_loader import load_sibling_script

check_third_party_compiles = load_sibling_script("check_third_party_compiles")


def _journal_record(
    *,
    crate: str,
    version: str,
    outcome: str,
    ts: str,
    miss_reason: "str | None" = None,
    latency_ns: int = 100_000_000,
) -> dict:
    """One zccache compile-journal record, using the real field names.

    `ts` is the record-WRITE time (ISO 8601 UTC, `Z` suffix), not a
    compile-start time -- matching zccache's own schema. `cwd` sits under
    `/registry/src/`, which is how the analyzer classifies a record as
    third-party rather than a workspace member.
    """
    crate_dir = f"/home/ci/.cargo/registry/src/index.crates.io-abcdef/{crate}-{version}"
    return {
        "ts": ts,
        "outcome": outcome,
        "miss_reason": miss_reason,
        "context_key": f"ctx-{crate}-{version}",
        "daemon_generation": 1,
        "compiler": "/home/ci/.rustup/toolchains/1.95.0-x86_64-unknown-linux-gnu/bin/rustc",
        "args": [
            "--crate-name",
            crate,
            "--edition=2021",
            f"{crate_dir}/src/lib.rs",
            "--crate-type",
            "lib",
        ],
        "cwd": crate_dir,
        "exit_code": 0,
        "session_id": "session-fixture",
        "latency_ns": latency_ns,
    }


# Two "Compiling <crate> vX.Y.Z" progress lines (hit_dep is journal-observed
# as a hit but still compiles from cargo's point of view -- the wrapper
# always runs, a cache hit just skips invoking rustc for real; no_record_dep
# has no journal record at all) plus one `fingerprint dirty for ... cause:
# FsStatusOutdated` line for miss_dep. fresh_dep deliberately has no line
# here at all -- that absence, combined with its Cargo.lock entry, is what
# makes it Fresh rather than any other bucket.
CARGO_LOG = "\n".join(
    [
        "   Compiling no_record_dep v2.0.0",
        "   Compiling hit_dep v1.0.0",
        "[2026-09-01T00:00:03.000000Z INFO  cargo::core::compiler::fingerprint] "
        "fingerprint dirty for miss_dep v0.4.0 "
        "(/home/ci/.cargo/registry/src/index.crates.io-abcdef/miss_dep-0.4.0): "
        "cause: FsStatusOutdated",
        "",
    ]
)

LOCKFILE = "\n".join(
    [
        "# This file is automatically @generated by Cargo.",
        "# It is not intended for manual editing.",
        "version = 3",
        "",
        "[[package]]",
        'name = "fresh_dep"',
        'version = "3.0.0"',
        'source = "registry+https://github.com/rust-lang/crates.io-index"',
        "",
        "[[package]]",
        'name = "hit_dep"',
        'version = "1.0.0"',
        'source = "registry+https://github.com/rust-lang/crates.io-index"',
        "",
        "[[package]]",
        'name = "miss_dep"',
        'version = "0.4.0"',
        'source = "registry+https://github.com/rust-lang/crates.io-index"',
        "",
        "[[package]]",
        'name = "no_record_dep"',
        'version = "2.0.0"',
        'source = "registry+https://github.com/rust-lang/crates.io-index"',
        "",
    ]
)


def _write_fixture(tmp_path: Path) -> dict:
    """Build the synthetic (journal, cargo log, lockfile) triple on disk.

    Bucket 1 (Fresh): `fresh_dep` -- in the lockfile, no journal record, no
    cargo log line at all.
    Bucket 2 (compiling_hit): `hit_dep` -- journal outcome `hit` plus a
    `Compiling` line.
    Bucket 3 (compiling_miss): `miss_dep` -- journal outcome `miss` /
    `context_not_found` plus a `fingerprint dirty for ... cause:
    FsStatusOutdated` line.
    Bucket 4 (compiling_no_record): `no_record_dep` -- a `Compiling` line,
    no journal record.
    """
    journal_path = tmp_path / "compile_journal.jsonl"
    records = [
        _journal_record(
            crate="hit_dep",
            version="1.0.0",
            outcome="hit",
            ts="2026-09-01T00:00:02.000000Z",
        ),
        _journal_record(
            crate="miss_dep",
            version="0.4.0",
            outcome="miss",
            miss_reason="context_not_found",
            ts="2026-09-01T00:00:03.000000Z",
        ),
    ]
    journal_path.write_text(
        "\n".join(json.dumps(record) for record in records) + "\n", encoding="utf-8"
    )

    cargo_log_path = tmp_path / "cargo-fingerprint.log"
    cargo_log_path.write_text(CARGO_LOG, encoding="utf-8")

    lockfile_path = tmp_path / "Cargo.lock"
    lockfile_path.write_text(LOCKFILE, encoding="utf-8")

    return {
        "journal": str(journal_path),
        "cargo_log": str(cargo_log_path),
        "lockfile": str(lockfile_path),
    }


def _fixture_argv(paths: dict, *, max_misses: int, max_dirty: int) -> list:
    return [
        paths["journal"],
        "--cargo-logs",
        paths["cargo_log"],
        "--lockfile",
        paths["lockfile"],
        "--max-misses",
        str(max_misses),
        "--max-dirty-third-party",
        str(max_dirty),
    ]


def _fixture_summary(tmp_path: Path) -> dict:
    """Run the real analyzer against the fixture once, for bucket assertions."""
    paths = _write_fixture(tmp_path)
    return check_third_party_compiles.analyze_compile_journal.analyze(
        [paths["journal"]],
        cargo_log_paths=[paths["cargo_log"]],
        repo_root=None,
        lockfiles=[paths["lockfile"]],
        dedupe=True,
    )


def test_bucket_counts_cover_all_four_buckets(tmp_path: Path) -> None:
    summary = _fixture_summary(tmp_path)
    buckets = summary["buckets"]
    assert buckets["fresh"] == 1
    assert buckets["compiling_hit"] == 1
    assert buckets["compiling_miss"] == 1
    assert buckets["compiling_no_record"] == 1
    assert (
        buckets["compiling_hit"]
        + buckets["compiling_miss"]
        + buckets["compiling_other"]
        == buckets["third_party_total"]
    )


def test_third_party_misses_count_only_the_miss_outcome(tmp_path: Path) -> None:
    summary = _fixture_summary(tmp_path)
    assert summary["third_party"]["misses"] == 1


def test_evaluate_ok_for_generous_thresholds(tmp_path: Path) -> None:
    summary = _fixture_summary(tmp_path)
    ok, lines = check_third_party_compiles.evaluate(
        summary, max_misses=100_000, max_dirty=100_000
    )
    assert ok
    assert any("OK" in line for line in lines)


def test_evaluate_fails_on_zero_max_misses(tmp_path: Path) -> None:
    summary = _fixture_summary(tmp_path)
    ok, lines = check_third_party_compiles.evaluate(
        summary, max_misses=0, max_dirty=100_000
    )
    assert not ok
    assert any("FAIL" in line for line in lines)
    assert any("soldr#3039" in line for line in lines)


def test_evaluate_never_fails_dirty_check_when_cargo_unavailable() -> None:
    summary = {
        "third_party": {"misses": 0, "records": []},
        "cargo": {
            "available": False,
            "third_party_dirty_units": 999_999,
            "dirty_reasons": {},
        },
        "buckets": {
            "third_party_total": 0,
            "fresh": None,
            "compiling_hit": 0,
            "compiling_miss": 0,
            "compiling_other": 0,
            "compiling_no_record": None,
        },
        "inputs": {"journal_files": []},
    }
    ok, lines = check_third_party_compiles.evaluate(summary, max_misses=0, max_dirty=0)
    assert ok
    assert any("skipped" in line for line in lines)


def test_main_report_only_thresholds_pass(tmp_path: Path) -> None:
    paths = _write_fixture(tmp_path)
    argv = _fixture_argv(paths, max_misses=100_000, max_dirty=100_000)
    assert check_third_party_compiles.main(argv) == 0


def test_main_zero_max_misses_fails(tmp_path: Path) -> None:
    paths = _write_fixture(tmp_path)
    argv = _fixture_argv(paths, max_misses=0, max_dirty=100_000)
    assert check_third_party_compiles.main(argv) == 1


def test_main_over_empty_directory_returns_zero_and_says_so(
    tmp_path: Path, capsys
) -> None:
    empty_dir = tmp_path / "does-not-exist"
    code = check_third_party_compiles.main(
        [str(empty_dir), "--max-misses", "0", "--max-dirty-third-party", "0"]
    )
    assert code == 0
    out = capsys.readouterr().out
    assert "nothing to check" in out


def test_summary_json_is_honoured_without_touching_journals(
    tmp_path: Path, capsys
) -> None:
    summary = {
        "third_party": {"misses": 3, "records": []},
        "cargo": {
            "available": True,
            "third_party_dirty_units": 1,
            "dirty_reasons": {"FsStatusOutdated": 1},
        },
        "buckets": {
            "third_party_total": 4,
            "fresh": 2,
            "compiling_hit": 2,
            "compiling_miss": 2,
            "compiling_other": 0,
            "compiling_no_record": 1,
        },
        "inputs": {"journal_files": ["hand-written.jsonl"]},
    }
    summary_path = tmp_path / "summary.json"
    summary_path.write_text(json.dumps(summary), encoding="utf-8")

    # A journal path that does not exist proves analyze() was never called on
    # it: if it had been, the numbers below (lifted straight from the
    # hand-written summary, not from any real journal) would not appear.
    argv = [
        str(tmp_path / "does-not-exist-journal-dir"),
        "--summary-json",
        str(summary_path),
        "--max-misses",
        "100000",
        "--max-dirty-third-party",
        "100000",
    ]
    code = check_third_party_compiles.main(argv)
    assert code == 0
    out = capsys.readouterr().out
    # No `cost` block in this hand-written summary, so the broad
    # `third_party.misses` fallback is used -- and the printed line has to say
    # so, or a future phase cannot tell which definition its threshold was
    # calibrated against.
    assert "third-party misses 3 (max 100000, miss|link_miss fallback)" in out
    assert "third-party dirty units 1 (max 100000)" in out
    assert "fresh=2 hit=2 miss=2 other=0 no-record=1" in out


def test_a_missing_summary_json_falls_back_to_the_journals(
    tmp_path: Path, capsys
) -> None:
    # The CI ratchet step runs after a `continue-on-error: true` report step.
    # If that step died before writing its JSON, the journals are still on
    # disk -- falling back to them keeps the gate live instead of silently
    # skipping exactly the run that went wrong.
    paths = _write_fixture(tmp_path)
    argv = [
        *_fixture_argv(paths, max_misses=0, max_dirty=100_000),
        "--summary-json",
        str(tmp_path / "never-written.json"),
    ]
    assert check_third_party_compiles.main(argv) == 1
    out = capsys.readouterr().out
    assert "could not read --summary-json" in out
    assert "third-party misses 1 (max 0, outcome==miss)" in out


def test_the_strict_miss_count_wins_over_the_broad_party_count(tmp_path: Path) -> None:
    # `third_party.misses` counts `miss | link_miss`; the ratchet's own
    # definition is the strict `outcome == "miss"` set the analyzer publishes
    # as `cost.third_party_miss_records`. A relink is a separate, much cheaper
    # event and must not spend the miss budget.
    summary = {
        "third_party": {"misses": 9},
        "cost": {"third_party_miss_records": 2},
        "cargo": {"available": False},
        "buckets": {},
        "inputs": {"journal_files": ["x.jsonl"]},
    }
    ok, lines = check_third_party_compiles.evaluate(summary, max_misses=2, max_dirty=0)
    assert ok
    assert any("third-party misses 2 (max 2, outcome==miss)" in line for line in lines)

    summary_path = tmp_path / "summary.json"
    summary_path.write_text(json.dumps(summary), encoding="utf-8")
    assert (
        check_third_party_compiles.main(
            [
                "--summary-json",
                str(summary_path),
                "--max-misses",
                "1",
                "--max-dirty-third-party",
                "0",
            ]
        )
        == 1
    )


def test_a_summary_json_that_is_not_an_object_is_a_wiring_problem(
    tmp_path: Path, capsys
) -> None:
    # A truncated artifact parses as valid JSON of the wrong shape. The
    # ratchet must report that and pass, not raise AttributeError and redden
    # the lane for a plumbing fault.
    summary_path = tmp_path / "summary.json"
    summary_path.write_text("[]", encoding="utf-8")
    code = check_third_party_compiles.main(
        [
            "--summary-json",
            str(summary_path),
            "--max-misses",
            "0",
            "--max-dirty-third-party",
            "0",
        ]
    )
    assert code == 0
    assert "nothing to check" in capsys.readouterr().out


def test_lockfiles_from_repo_still_honours_explicit_lockfiles(tmp_path: Path) -> None:
    # The flag used to discard `--lockfile` *and* discover nothing, which
    # silently collapsed the four-bucket join to `fresh: null` -- a number
    # that looks like "no Fresh crates" rather than "not measured".
    paths = _write_fixture(tmp_path)
    repo_root = tmp_path / "empty-repo"
    repo_root.mkdir()
    argv = [
        *_fixture_argv(paths, max_misses=100_000, max_dirty=100_000),
        "--lockfiles-from-repo",
        "--repo-root",
        str(repo_root),
        "--json-out",
        str(tmp_path / "summary-out.json"),
    ]
    assert check_third_party_compiles.main(argv) == 0
    written = json.loads((tmp_path / "summary-out.json").read_text(encoding="utf-8"))
    assert written["inputs"]["lockfiles"] == [paths["lockfile"]]
    assert written["buckets"]["fresh"] == 1
