//! A `cargo` shim that restores `RUSTUP_TOOLCHAIN` for nested builds
//! (soldr#3452, #3394).
//!
//! Soldr runs cargo by absolute path and puts that cargo's own directory first
//! on the child's search path. The `cargo` a nested build finds there is the
//! real toolchain binary, not rustup's proxy -- and the proxy is what normally
//! re-exports `RUSTUP_TOOLCHAIN` to everything below it. So a tool that runs
//! `env -u RUSTUP_TOOLCHAIN cargo build` from a temporary directory
//! (`dylint_testing` does) loses the variable for good, and a build script that
//! reads it -- `dylint_driver`'s -- dies with "environment variable not found:
//! RUSTUP_TOOLCHAIN".
//!
//! This module writes a tiny content-addressed `cargo` in front of the real one
//! that sets the variable when it is missing and execs the real cargo, which is
//! the proxy's contract. It is a plain exec, not a re-entry into soldr, so it
//! adds no caching or nesting behavior of its own.

use crate::core::{SoldrError, SoldrPaths};
use std::path::{Path, PathBuf};
use std::process::Command;

const SHIM_FORMAT_VERSION: &str = "v1";

/// The directory to put ahead of `real_cargo`'s own on the child's search path,
/// or `None` when the child has no `RUSTUP_TOOLCHAIN` to restore.
pub(crate) fn shim_dir_for(
    command: &Command,
    paths: &SoldrPaths,
    real_cargo: &Path,
) -> Result<Option<PathBuf>, SoldrError> {
    let Some(toolchain) =
        crate::toolchain_dir_name::effective_command_env(command, "RUSTUP_TOOLCHAIN")
    else {
        return Ok(None);
    };
    let Some(toolchain) = toolchain.to_str() else {
        return Ok(None);
    };
    materialize(paths, real_cargo, toolchain).map(Some)
}

fn materialize(
    paths: &SoldrPaths,
    real_cargo: &Path,
    toolchain: &str,
) -> Result<PathBuf, SoldrError> {
    let body = render(real_cargo, toolchain)?;
    let digest = {
        use sha2::{Digest, Sha256};
        format!("{:x}", Sha256::digest(body.as_bytes()))
    };
    let dir = paths
        .bin
        .join("cargo-shims")
        .join(SHIM_FORMAT_VERSION)
        .join(&digest[..20]);
    std::fs::create_dir_all(&dir)?;
    let name = format!(
        "cargo{}",
        crate::platform::executable::name::script_suffix()
    );
    crate::linker_shim::write_content_addressed_shim(&dir.join(name), &body)?;
    Ok(dir)
}

fn render(real_cargo: &Path, toolchain: &str) -> Result<String, SoldrError> {
    let real = real_cargo.to_str().ok_or_else(|| {
        SoldrError::Other(format!(
            "cargo path is not valid UTF-8: {}",
            real_cargo.display()
        ))
    })?;
    if crate::platform::host::facts::os() == crate::platform::host::facts::HostOs::Windows {
        let toolchain = toolchain.replace('%', "%%");
        let real = real.replace('%', "%%");
        return Ok(format!(
            "@echo off\r\nif not defined RUSTUP_TOOLCHAIN set \"RUSTUP_TOOLCHAIN={toolchain}\"\r\n\"{real}\" %*\r\n"
        ));
    }
    let quote = |value: &str| format!("'{}'", value.replace('\'', "'\\''"));
    // An explicit `if`, not `${VAR:=word}`: inside double quotes the single
    // quotes of `word` stay literal, which would put quote characters into the
    // variable's value.
    Ok(format!(
        "#!/bin/sh\n# generated by soldr; restores what rustup's cargo proxy would export\n\
         if [ -z \"${{RUSTUP_TOOLCHAIN:-}}\" ]; then RUSTUP_TOOLCHAIN={}; fi\n\
         export RUSTUP_TOOLCHAIN\nexec {} \"$@\"\n",
        quote(toolchain),
        quote(real)
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn windows() -> bool {
        crate::platform::host::facts::os() == crate::platform::host::facts::HostOs::Windows
    }

    #[test]
    fn a_child_without_a_toolchain_gets_no_shim() {
        let temp = tempfile::tempdir().unwrap();
        let paths = SoldrPaths::with_root(temp.path().to_path_buf());
        let mut command = Command::new("cargo");
        command.env_remove("RUSTUP_TOOLCHAIN");
        // The process environment may or may not hold one; only the command's
        // own value is asserted on below.
        command.env("RUSTUP_TOOLCHAIN", "");
        assert!(shim_dir_for(&command, &paths, Path::new("/x/cargo"))
            .unwrap()
            .is_none());
    }

    #[test]
    fn the_shim_is_content_addressed_and_names_the_toolchain_and_real_cargo() {
        let temp = tempfile::tempdir().unwrap();
        let paths = SoldrPaths::with_root(temp.path().to_path_buf());
        let mut command = Command::new("cargo");
        command.env(
            "RUSTUP_TOOLCHAIN",
            "nightly-2026-05-28-x86_64-unknown-linux-gnu",
        );
        let real = Path::new("/tc/bin/cargo");

        let first = shim_dir_for(&command, &paths, real).unwrap().unwrap();
        let again = shim_dir_for(&command, &paths, real).unwrap().unwrap();
        assert_eq!(first, again, "stable path for identical content");
        command.env("RUSTUP_TOOLCHAIN", "stable");
        let other = shim_dir_for(&command, &paths, real).unwrap().unwrap();
        assert_ne!(first, other, "a different toolchain is a different shim");

        let name = format!(
            "cargo{}",
            crate::platform::executable::name::script_suffix()
        );
        let body = std::fs::read_to_string(first.join(name)).unwrap();
        assert!(
            body.contains("nightly-2026-05-28-x86_64-unknown-linux-gnu"),
            "{body}"
        );
        assert!(body.contains("/tc/bin/cargo"), "{body}");
        if !windows() {
            assert!(
                body.contains("RUSTUP_TOOLCHAIN='") && body.contains("exec "),
                "{body}"
            );
        }
    }

    #[test]
    fn a_hostile_path_cannot_break_out_of_its_quoting() {
        if windows() {
            return;
        }
        let body = render(Path::new("/it's/a trap/cargo"), "t'c").unwrap();
        assert!(body.contains(r#"'/it'\''s/a trap/cargo'"#), "{body}");
        assert!(body.contains(r#"'t'\''c'"#), "{body}");
    }

    /// Run the generated shim for real, the way `env -u RUSTUP_TOOLCHAIN cargo`
    /// does: the fake "real cargo" must see exactly the toolchain, with no
    /// stray quote characters, and must keep a caller-set value.
    #[test]
    fn the_shim_restores_the_variable_exactly_and_keeps_a_caller_value() {
        if windows() {
            return;
        }
        let temp = tempfile::tempdir().unwrap();
        let real = temp.path().join("real-cargo");
        std::fs::write(
            &real,
            "#!/bin/sh\nprintf '%s|%s' \"${RUSTUP_TOOLCHAIN-<unset>}\" \"$*\"\n",
        )
        .unwrap();
        crate::platform::fs::permissions::make_executable(&real).unwrap();
        let paths = SoldrPaths::with_root(temp.path().join("root"));
        let mut probe = Command::new("cargo");
        probe.env(
            "RUSTUP_TOOLCHAIN",
            "nightly-2026-05-28-x86_64-unknown-linux-gnu",
        );
        let dir = shim_dir_for(&probe, &paths, &real).unwrap().unwrap();
        let shim = dir.join("cargo");

        let restored = Command::new(&shim)
            .env_remove("RUSTUP_TOOLCHAIN")
            .args(["build", "--release"])
            .output()
            .unwrap();
        assert_eq!(
            String::from_utf8_lossy(&restored.stdout),
            "nightly-2026-05-28-x86_64-unknown-linux-gnu|build --release"
        );
        let kept = Command::new(&shim)
            .env("RUSTUP_TOOLCHAIN", "caller-choice")
            .output()
            .unwrap();
        assert_eq!(String::from_utf8_lossy(&kept.stdout), "caller-choice|");
    }
}
