#[derive(Debug, Clone)]
enum DriftSignal {
    Drifted([u8; 32]),
    AlreadyIndexed(#[allow(dead_code)] [u8; 32]),
}

/// The on-disk archive a `CookLookup` hit already names, when it can stand in
/// for a fresh pack (soldr#3117).
///
/// An exact recipe match means the indexed artifact was cooked from this very
/// dependency graph with this rustc; when its `<sha256>.tar.zst` is still
/// present at the recorded size there is nothing a re-pack would add, and a
/// level-19 zstd pack of the trimmed tree is the most expensive step of a
/// warm cook (minutes for the CI stable tree, against a compile the compile
/// cache already serves in about one). A drifted match, a missing file, or a
/// size mismatch all return `None` and take the pack path as before.
fn already_indexed_archive(cook_dir: &Path, outcome: &CookLookupOutcome) -> Option<PathBuf> {
    let CookLookupOutcome::Hit {
        sha256,
        size_bytes,
        exact_recipe_match: true,
        ..
    } = outcome
    else {
        return None;
    };
    let path = cook_archive::artifact_path_for_sha(cook_dir, sha256);
    let on_disk = std::fs::metadata(&path).ok()?;
    (on_disk.is_file() && on_disk.len() == *size_bytes).then_some(path)
}

fn emit_indexed_line(
    packed: &PackedCookArchive,
    origin: Option<&str>,
    compile_duration_ms: u64,
    save_elapsed_ms: u64,
) {
    eprintln!(
        "{}",
        format_indexed_line(
            packed,
            origin,
            compile_duration_ms,
            save_elapsed_ms
        )
    );
}

fn format_indexed_line(
    packed: &PackedCookArchive,
    origin: Option<&str>,
    compile_duration_ms: u64,
    save_elapsed_ms: u64,
) -> String {
    let mib = packed.size_bytes as f64 / 1024.0 / 1024.0;
    let origin_field = origin.unwrap_or("none");
    format!(
        "{}  sha256={}  size_bytes={}  size={mib:.1} MiB  elapsed_ms={save_elapsed_ms}  compile_elapsed_ms={compile_duration_ms}  decision=save  origin={origin_field}",
        green_indexed_prefix(),
        sha_abbrev(&packed.sha256),
        packed.size_bytes,
    )
}

fn build_cook_cmd_summary(args: &CookArgs) -> String {
    let mut parts = vec!["cook".to_string()];
    if args.release {
        parts.push("--release".to_string());
    }
    if let Some(p) = args.profile.as_deref() {
        parts.push(format!("--profile={p}"));
    }
    if let Some(t) = args.target.as_deref() {
        parts.push(format!("--target={t}"));
    }
    if args.workspace {
        parts.push("--workspace".to_string());
    }
    for pkg in &args.packages {
        parts.push(format!("-p {pkg}"));
    }
    parts.join(" ")
}

/// Remove cargo-chef-generated `plugin = false` / `plugin = true`
/// target fields from the prepared recipe's embedded TOML manifests.
/// Newer Cargo warns on these obsolete keys during `cargo chef cook`,
/// but they are generated by cargo-chef's metadata round-trip rather
/// than by the user's checked-in manifests.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq)]
struct RecipeSanitizeReport {
    plugin_keys_removed: usize,
    path_dependencies_rewritten: usize,
    patches_removed: usize,
}

impl RecipeSanitizeReport {
    fn needs_exact_build(self) -> bool {
        self.path_dependencies_rewritten > 0 || self.patches_removed > 0
    }
}

fn sanitize_cargo_chef_recipe(
    recipe_path: &Path,
) -> Result<RecipeSanitizeReport, SoldrError> {
    let raw = std::fs::read_to_string(recipe_path).map_err(|e| {
        SoldrError::Other(format!(
            "soldr cook: failed to read cargo-chef recipe {}: {e}",
            recipe_path.display()
        ))
    })?;
    let mut recipe: serde_json::Value = serde_json::from_str(&raw).map_err(|e| {
        SoldrError::Other(format!(
            "soldr cook: failed to parse cargo-chef recipe {}: {e}",
            recipe_path.display()
        ))
    })?;

    let mut report = RecipeSanitizeReport::default();
    let excluded = recipe_excluded_paths(&recipe);
    let locked_versions = recipe_locked_path_versions(&recipe);
    let Some(manifests) = recipe
        .get_mut("skeleton")
        .and_then(|value| value.get_mut("manifests"))
        .and_then(|value| value.as_array_mut())
    else {
        return Ok(RecipeSanitizeReport::default());
    };

    for manifest in manifests {
        let relative = manifest
            .get("relative_path")
            .and_then(|value| value.as_str())
            .unwrap_or_default()
            .to_string();
        let Some(contents_value) = manifest.get_mut("contents") else {
            continue;
        };
        let Some(contents) = contents_value.as_str() else {
            continue;
        };
        let (sanitized, count) = strip_generated_plugin_lines(contents);
        report.plugin_keys_removed += count;
        let owner = manifest_dir_of(&relative);
        let (sanitized, rewritten, patches_removed) = rewrite_excluded_paths_to_registry(
            &sanitized,
            &owner,
            &excluded,
            &locked_versions,
        );
        report.path_dependencies_rewritten += rewritten;
        report.patches_removed += patches_removed;
        if count + rewritten + patches_removed > 0 {
            *contents_value = serde_json::Value::String(sanitized);
        }
    }

    if report != RecipeSanitizeReport::default() {
        let encoded = serde_json::to_vec(&recipe).map_err(|e| {
            SoldrError::Other(format!(
                "soldr cook: failed to serialize sanitized recipe {}: {e}",
                recipe_path.display()
            ))
        })?;
        std::fs::write(recipe_path, encoded).map_err(|e| {
            SoldrError::Other(format!(
                "soldr cook: failed to write sanitized recipe {}: {e}",
                recipe_path.display()
            ))
        })?;
    }

    Ok(report)
}

fn recipe_locked_path_versions(
    recipe: &serde_json::Value,
) -> std::collections::BTreeMap<String, Vec<String>> {
    let Some(lock) = recipe
        .get("skeleton")
        .and_then(|value| value.get("lock_file"))
        .and_then(|value| value.as_str())
    else {
        return std::collections::BTreeMap::new();
    };
    let Ok(lock) = lock.parse::<toml::Value>() else {
        return std::collections::BTreeMap::new();
    };
    let mut versions = std::collections::BTreeMap::<String, Vec<String>>::new();
    for (name, version) in lock
        .get("package")
        .and_then(toml::Value::as_array)
        .into_iter()
        .flatten()
        .filter(|package| package.get("source").is_none())
        .filter_map(|package| {
            Some((
                package.get("name")?.as_str()?.to_string(),
                package.get("version")?.as_str()?.to_string(),
            ))
        })
    {
        versions.entry(name).or_default().push(version);
    }
    versions
}

fn recipe_excluded_paths(recipe: &serde_json::Value) -> Vec<String> {
    let Some(manifests) = recipe
        .get("skeleton")
        .and_then(|value| value.get("manifests"))
        .and_then(|value| value.as_array())
    else {
        return Vec::new();
    };
    let Some(root) = manifests.iter().find(|manifest| {
        manifest.get("relative_path").and_then(|value| value.as_str()) == Some("Cargo.toml")
    }) else {
        return Vec::new();
    };
    let Some(contents) = root.get("contents").and_then(|value| value.as_str()) else {
        return Vec::new();
    };
    contents
        .parse::<toml::Value>()
        .ok()
        .and_then(|doc| doc.get("workspace")?.get("exclude")?.as_array().cloned())
        .unwrap_or_default()
        .into_iter()
        .filter_map(|value| value.as_str().map(|path| join_manifest_relative("", path)))
        .collect()
}

fn rewrite_excluded_paths_to_registry(
    contents: &str,
    owner: &str,
    excluded: &[String],
    locked_versions: &std::collections::BTreeMap<String, Vec<String>>,
) -> (String, usize, usize) {
    let Ok(mut doc) = contents.parse::<toml::Value>() else {
        return (contents.to_string(), 0, 0);
    };
    let mut rewritten = 0usize;
    rewrite_dependency_tables(
        &mut doc,
        owner,
        excluded,
        locked_versions,
        &mut rewritten,
    );

    let mut patches_removed = 0usize;
    if let Some(patches) = doc.get_mut("patch").and_then(|value| value.as_table_mut()) {
        for source in patches
            .iter_mut()
            .filter_map(|(_, value)| value.as_table_mut())
        {
            let before = source.len();
            source.retain(|_, spec| {
                let excluded_patch = spec
                    .get("path")
                    .and_then(toml::Value::as_str)
                    .is_some_and(|path| path_is_excluded(owner, path, excluded));
                !excluded_patch
            });
            patches_removed += before - source.len();
        }
    }
    let encoded = toml::to_string(&doc).unwrap_or_else(|_| contents.to_string());
    (encoded, rewritten, patches_removed)
}

fn rewrite_dependency_tables(
    doc: &mut toml::Value,
    owner: &str,
    excluded: &[String],
    locked_versions: &std::collections::BTreeMap<String, Vec<String>>,
    rewritten: &mut usize,
) {
    let Some(table) = doc.as_table_mut() else { return };
    for name in ["dependencies", "dev-dependencies", "build-dependencies"] {
        rewrite_dependency_table(
            table.get_mut(name),
            owner,
            excluded,
            locked_versions,
            rewritten,
        );
    }
    if let Some(workspace) = table.get_mut("workspace").and_then(toml::Value::as_table_mut) {
        rewrite_dependency_table(
            workspace.get_mut("dependencies"),
            owner,
            excluded,
            locked_versions,
            rewritten,
        );
    }
    if let Some(targets) = table.get_mut("target").and_then(toml::Value::as_table_mut) {
        for (_, target) in targets.iter_mut() {
            let Some(target) = target.as_table_mut() else { continue };
            for name in ["dependencies", "dev-dependencies", "build-dependencies"] {
                rewrite_dependency_table(
                    target.get_mut(name),
                    owner,
                    excluded,
                    locked_versions,
                    rewritten,
                );
            }
        }
    }
}

fn rewrite_dependency_table(
    value: Option<&mut toml::Value>,
    owner: &str,
    excluded: &[String],
    locked_versions: &std::collections::BTreeMap<String, Vec<String>>,
    rewritten: &mut usize,
) {
    let Some(dependencies) = value.and_then(toml::Value::as_table_mut) else { return };
    for (name, value) in dependencies.iter_mut() {
        let Some(spec) = value.as_table_mut() else {
            continue;
        };
        let Some(path) = spec.get("path").and_then(toml::Value::as_str) else { continue };
        if path_is_excluded(owner, path, excluded) {
            let package_name = spec
                .get("package")
                .and_then(toml::Value::as_str)
                .unwrap_or(name);
            let Some(requirement) = spec
                .get("version")
                .and_then(toml::Value::as_str)
                .and_then(|value| semver::VersionReq::parse(value).ok())
            else {
                continue;
            };
            let candidates: Vec<&str> = locked_versions
                .get(package_name)
                .into_iter()
                .flatten()
                .filter_map(|value| {
                    semver::Version::parse(value)
                        .ok()
                        .filter(|version| requirement.matches(version))
                        .map(|_| value.as_str())
                })
                .collect();
            let [version] = candidates.as_slice() else {
                continue;
            };
            spec.remove("path");
            spec.insert(
                "version".to_string(),
                toml::Value::String(format!("={version}")),
            );
            *rewritten += 1;
        }
    }
}

fn path_is_excluded(owner: &str, path: &str, excluded: &[String]) -> bool {
    let resolved = join_manifest_relative(owner, path);
    excluded
        .iter()
        .any(|prefix| resolved == *prefix || resolved.starts_with(&format!("{prefix}/")))
}

/// Path dependencies the recipe skeleton never materializes (soldr#2788).
///
/// Returns `(dependency, depending crate)` pairs.
///
/// cargo-chef's skeleton lists the manifests it intends to stub. A crate that
/// depends on a path OUTSIDE that set -- typically a sibling repo vendored as
/// a git submodule with its own `[workspace]`, so it sits in the root
/// manifest's `exclude` rather than its `members` -- gets compiled during cook
/// with an `--extern` pointing at artifacts nothing produced:
///
/// ```text
/// error: extern location for zccache_cli_core does not exist
/// ```
///
/// Cook then degrades with "continuing without cooked deps", so the BUILD
/// STILL PASSES while no cache layer is saved and every later run repeats the
/// full cold dependency build. Detecting the layout up front converts ~190s of
/// silent waste into one honest line.
///
/// The deeper fix -- actually cooking these workspaces -- is soldr#2791.
pub(crate) fn unmaterializable_path_deps(recipe: &serde_json::Value) -> Vec<(String, String)> {
    let Some(manifests) = recipe
        .get("skeleton")
        .and_then(|s| s.get("manifests"))
        .and_then(|m| m.as_array())
    else {
        return Vec::new();
    };

    let present: std::collections::HashSet<String> = manifests
        .iter()
        .filter_map(|m| m.get("relative_path").and_then(|p| p.as_str()))
        .map(manifest_dir_of)
        .collect();

    let mut found = Vec::new();
    for manifest in manifests {
        let Some(rel) = manifest.get("relative_path").and_then(|p| p.as_str()) else {
            continue;
        };
        let Some(contents) = manifest.get("contents").and_then(|c| c.as_str()) else {
            continue;
        };
        let Ok(doc) = contents.parse::<toml::Value>() else {
            continue;
        };
        let owner_dir = manifest_dir_of(rel);
        for table in ["dependencies", "dev-dependencies", "build-dependencies"] {
            let Some(deps) = doc.get(table).and_then(|d| d.as_table()) else {
                continue;
            };
            for (name, spec) in deps {
                let Some(path) = spec.get("path").and_then(|p| p.as_str()) else {
                    continue;
                };
                let resolved = join_manifest_relative(&owner_dir, path);
                if !present.contains(&resolved) {
                    found.push((name.clone(), rel.to_string()));
                }
            }
        }
    }
    found.sort();
    found.dedup();
    found
}

/// `crates\soldr-cli\Cargo.toml` -> `crates/soldr-cli`; root -> `""`.
fn manifest_dir_of(relative_path: &str) -> String {
    let unified = relative_path.replace('\\', "/");
    unified
        .strip_suffix("Cargo.toml")
        .unwrap_or(&unified)
        .trim_end_matches('/')
        .to_string()
}

/// Resolve a manifest-relative `path = "../../x"` against its owner directory.
fn join_manifest_relative(owner_dir: &str, path: &str) -> String {
    let mut parts: Vec<&str> = if owner_dir.is_empty() {
        Vec::new()
    } else {
        owner_dir.split('/').collect()
    };
    let unified_path = path.replace('\\', "/");
    for segment in unified_path.split('/') {
        match segment {
            "" | "." => {}
            ".." => {
                parts.pop();
            }
            other => parts.push(other),
        }
    }
    parts.join("/")
}

fn strip_generated_plugin_lines(contents: &str) -> (String, usize) {
    let mut out = String::with_capacity(contents.len());
    let mut removed = 0usize;
    for line in contents.split_inclusive('\n') {
        let trimmed = line.trim();
        if matches!(trimmed, "plugin = false" | "plugin = true") {
            removed += 1;
            continue;
        }
        out.push_str(line);
    }
    (out, removed)
}

/// Run the `cook` strip preset against the workspace's `target/` directory.
///
/// Best-effort: a missing or partially-populated `target/` (the heavy
/// case is when cargo wrote into `target/<triple>/...` and the
/// stripper just finds nothing) is not an error — the trim only ever
/// reduces output. Failures are surfaced on stderr but never abort
/// the cook command (the artifacts are already built and valid).
fn run_cook_target_trim(manifest_dir: &Path) {
    let target_dir = manifest_dir.join("target");
    if !target_dir.is_dir() {
        return;
    }
    let opts = StripTargetOptions::cook(target_dir.clone());
    match strip_target(&opts) {
        Ok(report) => {
            if report.deleted == 0 {
                return;
            }
            let mib = report.reclaimed_bytes as f64 / 1024.0 / 1024.0;
            eprintln!(
                "soldr cook: trimmed {} cargo-recreatable entries from target/ ({mib:.1} MiB reclaimed)",
                report.deleted,
            );
        }
        Err(err) => {
            eprintln!(
                "soldr cook: target/ trim failed at {}: {err} (cook output is still valid)",
                target_dir.display()
            );
        }
    }
}

/// Argv for `cargo chef prepare --recipe-path <path>`, ready to feed
/// through the cargo front door.
pub(crate) fn build_chef_prepare_args(ctx: &CookContext) -> Vec<String> {
    vec![
        "chef".to_string(),
        "prepare".to_string(),
        "--recipe-path".to_string(),
        ctx.recipe_path.display().to_string(),
    ]
}

/// Argv for `cargo chef cook ...`, ready to feed through the cargo front
/// door.
pub(crate) fn build_chef_cook_args(ctx: &CookContext, args: &CookArgs) -> Vec<String> {
    let mut out = vec![
        "chef".to_string(),
        "cook".to_string(),
        "--recipe-path".to_string(),
        ctx.recipe_path.display().to_string(),
    ];
    if args.release {
        out.push("--release".to_string());
    }
    if let Some(profile) = args.profile.as_ref() {
        out.push("--profile".to_string());
        out.push(profile.clone());
    }
    if let Some(target) = args.target.as_ref() {
        out.push("--target".to_string());
        out.push(target.clone());
    }
    if args.workspace {
        out.push("--workspace".to_string());
    }
    for pkg in &args.packages {
        out.push("--package".to_string());
        out.push(pkg.clone());
    }
    // No `--` separator: cargo-chef's clap parser treats `--` as the end of
    // options and rejects everything after it as an unexpected positional
    // ("error: unexpected argument '--all-targets' found"). `soldr cook`'s
    // own `--` only delimits its parser from cargo-chef's; the forwarded
    // flags are cargo-chef options and must land in its option region.
    out.extend(args.passthrough.iter().cloned());
    out
}

/// Argv for the exact post-chef build used when the portable recipe had to
/// redirect excluded sibling workspaces to published packages.
pub(crate) fn build_exact_cook_args(args: &CookArgs) -> Vec<String> {
    let mut out = vec!["build".to_string()];
    if args.release {
        out.push("--release".to_string());
    }
    if let Some(profile) = args.profile.as_ref() {
        out.push("--profile".to_string());
        out.push(profile.clone());
    }
    if let Some(target) = args.target.as_ref() {
        out.push("--target".to_string());
        out.push(target.clone());
    }
    if args.workspace {
        out.push("--workspace".to_string());
    }
    for pkg in &args.packages {
        out.push("--package".to_string());
        out.push(pkg.clone());
    }
    out.extend(args.passthrough.iter().cloned());
    out
}
