//! Content-addressed Linux clang driver shims, and reld path injection.
//!
//! Split out of `linker.rs` to stay under the per-file line ceiling
//! (soldr#3276): this module has one cohesive job -- materializing a
//! driver-only executable shim so a Linux clang driver argument never enters
//! Cargo's `CARGO_TARGET_<TRIPLE>_RUSTFLAGS`, which would silently replace a
//! project's own `[build] rustflags` (soldr#3277) -- plus the reld-specific
//! path substitution that runs just before a shim is materialized.

use crate::core::SoldrError;
use sha2::{Digest, Sha256};
use std::path::Path;
use std::sync::atomic::{AtomicU64, Ordering};

use crate::linker::{target_kind, LinkerInjection, TargetKind};

const LINKER_SHIM_FORMAT_VERSION: &str = "v1";
static LINKER_SHIM_TEMP_SEQUENCE: AtomicU64 = AtomicU64::new(0);

/// Replace the bare `reld` token in an explicit linker injection with a
/// verified absolute executable path resolved before Cargo starts.
pub fn inject_resolved_reld(
    injection: &mut LinkerInjection,
    reld: &Path,
) -> Result<(), SoldrError> {
    let reld = reld.to_str().ok_or_else(|| {
        SoldrError::Other(format!(
            "managed reld path is not valid UTF-8: {}",
            reld.display()
        ))
    })?;
    let mut replaced = false;
    if injection.linker.as_deref() == Some("reld") {
        injection.linker = Some(reld.to_string());
        replaced = true;
    }
    if let Some(flags) = injection.rustflags.as_mut() {
        if flags.contains("--ld-path=reld") {
            *flags = flags.replacen("--ld-path=reld", &format!("--ld-path={reld}"), 1);
            replaced = true;
        }
    }
    if replaced {
        Ok(())
    } else {
        Err(SoldrError::Other(
            "explicit reld linker selection produced no reld injection".to_string(),
        ))
    }
}

/// Move a Linux clang driver argument out of target-scoped rustflags and into
/// a content-addressed executable shim.
///
/// Cargo does not merge `CARGO_TARGET_<TRIPLE>_RUSTFLAGS` with
/// `[build] rustflags`; the environment value replaces the project setting.
/// A linker shim carries the driver-only argument without entering Cargo's
/// rustflags precedence at all. Its content digest is embedded in the path so
/// the existing `CARGO_TARGET_*_LINKER` cache-key input changes whenever the
/// generated command changes.
pub fn materialize_linker_driver_shim(
    paths: &crate::core::SoldrPaths,
    target: &str,
    injection: &mut LinkerInjection,
) -> Result<(), SoldrError> {
    if target_kind(target) != TargetKind::Linux || injection.linker.as_deref() != Some("clang") {
        return Ok(());
    }
    let Some(rustflags) = injection.rustflags.as_deref() else {
        return Ok(());
    };
    let Some(driver_arg) = rustflags.strip_prefix("-C link-arg=") else {
        return Ok(());
    };

    let body = render_linker_driver_shim(driver_arg);
    let digest = format!("{:x}", Sha256::digest(body.as_bytes()));
    let dir = paths
        .bin
        .join("linker-shims")
        .join(LINKER_SHIM_FORMAT_VERSION);
    std::fs::create_dir_all(&dir)?;
    let suffix = crate::platform::executable::name::script_suffix();
    let path = dir.join(format!("clang-{}{suffix}", &digest[..20]));
    write_content_addressed_shim(&path, &body)?;

    injection.linker = Some(path.to_string_lossy().into_owned());
    injection.rustflags = None;
    Ok(())
}

fn render_linker_driver_shim(driver_arg: &str) -> String {
    if crate::platform::host::facts::os() == crate::platform::host::facts::HostOs::Windows {
        render_windows_linker_driver_shim(driver_arg)
    } else {
        format!(
            "#!/bin/sh\n# generated by soldr; content-addressed linker driver\nexec clang {} \"$@\"\n",
            shell_single_quote(driver_arg)
        )
    }
}

pub(crate) fn render_windows_linker_driver_shim(driver_arg: &str) -> String {
    // The generated values are one driver argument and cannot contain a
    // double quote (Windows paths cannot either). Quoting the whole argument
    // protects spaces and cmd metacharacters; doubling percent signs prevents
    // environment-variable expansion before clang receives the value.
    let escaped = driver_arg.replace('%', "%%");
    format!("@echo off\r\nclang \"{escaped}\" %*\r\n")
}

fn shell_single_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

fn write_content_addressed_shim(path: &Path, body: &str) -> Result<(), SoldrError> {
    if std::fs::read_to_string(path).ok().as_deref() == Some(body) {
        return Ok(());
    }
    let sequence = LINKER_SHIM_TEMP_SEQUENCE.fetch_add(1, Ordering::Relaxed);
    let temp = path.with_extension(format!("tmp-{}-{sequence}", std::process::id()));
    std::fs::write(&temp, body)?;
    crate::platform::fs::permissions::make_executable(&temp).map_err(SoldrError::Io)?;
    match std::fs::rename(&temp, path) {
        Ok(()) => Ok(()),
        Err(_) if std::fs::read_to_string(path).ok().as_deref() == Some(body) => {
            let _ = std::fs::remove_file(&temp);
            Ok(())
        }
        Err(error) => {
            let _ = std::fs::remove_file(&temp);
            Err(SoldrError::Io(error))
        }
    }
}
